// tslint:disable-next-line: max-line-length
import { createToken, SyntaxKind } from 'typescript';
import { SourceFileDescriptor } from '../descriptors';
import { TargetFileDescriptor } from '../descriptors/TargetFileDescriptor';
import { INodeBuilder } from '../interfaces/INodeBuilder';
import { tools } from '../tools';
import { NodeBuilder } from './NodeBuilder';

// https://medium.com/@marvin_78330/creating-typescript-with-the-typescript-compiler-ac3370701d7f

// TODO: This is a TargetFileGenerator !! Replace SourceFileDescriptor...
export class SourceToTargetFileConverter {

  buildNodes(targetFilePath: string, sourceFileDescriptor: SourceFileDescriptor, nodeBuilder: INodeBuilder): TargetFileDescriptor {
    const result = new TargetFileDescriptor(targetFilePath);

    const builder = new NodeBuilder();

    builder.addMultiLineComment(
      'File generated by Interface generator (dotup.dotup-vscode-interface-generator)',
      // tslint:disable-next-line: newline-per-chained-call
      `Date: ${tools.getCurrentIsoDate()}`
    );

    builder.add(createToken(SyntaxKind.NewLineTrivia));

    // Imports
    if (sourceFileDescriptor.importDeclarations.length >= 0) {
      sourceFileDescriptor.importDeclarations.forEach(item => builder.add(item));
      // New line
      builder.add(createToken(SyntaxKind.NewLineTrivia));
    }

    // For each class
    sourceFileDescriptor.classDescriptors.forEach(item => {

      // this.out.appendLine(`Build nodes for ${item.interfaceName}`);

      const interfaceNodes = nodeBuilder.buildNodes(item);
      builder.add(interfaceNodes);

    });

    result.nodes = builder.nodes;

    return result;
  }

}
